ASSETS_DIR_BG_VIDEO = "assets/video"
ASSETS_DIR_BG_AUDIO = "assets/audio"
OUTPUT_DIR          = "results"
TEMP_DIR            = "temp"
PROPERTIES_PATH     = "_properties.env"
CONFIG_PATH         = "_config.env"