PROPERTIES_DEFAULTS = {
    "CLIP_LENGTH_MIN": 20,
    "CLIP_LENGTH_MAX": 60,
    "SCREEN_RATIO": 9 / 16,
    "IMAGE_PADDING": 15
}

PROPERTIES_TYPES = {
    "CLIP_LENGTH_MIN": int,
    "CLIP_LENGTH_MAX": int,
    "SCREEN_RATIO": float,
    "IMAGE_PADDING": int
}