ASSETS_DIR_BG_VIDEO = "assets/video"
ASSETS_DIR_BG_AUDIO = "assets/audio"
OUTPUT_DIR          = "results"
TEMP_DIR            = "temp"
PROPERTIES_PATH     = "_properties.env"
CONFIG_PATH         = "_config.env"
DAJAVU_PATH         = "dejavu.json"
REDDIT_USER_AGENT   = "Mozilla/5.0 (Windows; Windows NT 10.0;; en-US) AppleWebKit/600.42 (KHTML, like Gecko) Chrome/50.0.2869.131 Safari/534"